/*
 * This file is generated by jOOQ.
 */
package com.simple.spring.mysql.jooq.tables.records;


import com.simple.spring.mysql.jooq.tables.Tutorials;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TutorialsRecord extends UpdatableRecordImpl<TutorialsRecord> implements Record4<Long, String, String, Byte> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>test_db.tutorials.id</code>.
     */
    public TutorialsRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>test_db.tutorials.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>test_db.tutorials.title</code>.
     */
    public TutorialsRecord setTitle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>test_db.tutorials.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test_db.tutorials.description</code>.
     */
    public TutorialsRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>test_db.tutorials.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>test_db.tutorials.published</code>.
     */
    public TutorialsRecord setPublished(Byte value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>test_db.tutorials.published</code>.
     */
    public Byte getPublished() {
        return (Byte) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, Byte> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, String, Byte> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Tutorials.TUTORIALS.ID;
    }

    @Override
    public Field<String> field2() {
        return Tutorials.TUTORIALS.TITLE;
    }

    @Override
    public Field<String> field3() {
        return Tutorials.TUTORIALS.DESCRIPTION;
    }

    @Override
    public Field<Byte> field4() {
        return Tutorials.TUTORIALS.PUBLISHED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Byte component4() {
        return getPublished();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public Byte value4() {
        return getPublished();
    }

    @Override
    public TutorialsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TutorialsRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public TutorialsRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public TutorialsRecord value4(Byte value) {
        setPublished(value);
        return this;
    }

    @Override
    public TutorialsRecord values(Long value1, String value2, String value3, Byte value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TutorialsRecord
     */
    public TutorialsRecord() {
        super(Tutorials.TUTORIALS);
    }

    /**
     * Create a detached, initialised TutorialsRecord
     */
    public TutorialsRecord(Long id, String title, String description, Byte published) {
        super(Tutorials.TUTORIALS);

        setId(id);
        setTitle(title);
        setDescription(description);
        setPublished(published);
    }
}
