/*
 * This file is generated by jOOQ.
 */
package com.simple.spring.mysql.jooq;


import com.simple.spring.mysql.jooq.tables.Tutorials;


/**
 * Convenience access to all tables in test_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test_db.tutorials</code>.
     */
    public static final Tutorials TUTORIALS = Tutorials.TUTORIALS;
}
