/*
 * This file is generated by jOOQ.
 */
package com.simple.spring.mysql.jooq;


import com.simple.spring.mysql.jooq.tables.Tutorials;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestDb extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test_db</code>
     */
    public static final TestDb TEST_DB = new TestDb();

    /**
     * The table <code>test_db.tutorials</code>.
     */
    public final Tutorials TUTORIALS = Tutorials.TUTORIALS;

    /**
     * No further instances allowed
     */
    private TestDb() {
        super("test_db", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Tutorials.TUTORIALS);
    }
}
